### ISSUE TITLE
Screen scan tanaman

### ISSUE THREAD

**Issue by edoaurahman** [PBL-2024/herba_scan#1]
Slicing desain dari figma bagian scan tanaman
[link figma](https://www.figma.com/design/PybxVNmH6CrOS0jSsSBekP/HerbaScan?node-id=0-1&node-type=canvas&t=SBSE37gBJQuQLfih-0)

**Comment by edoaurahman** [comment]
Progresnya mana bang, sini tak bantu

**Comment by rhanilham** [comment]
on progres bang, slicing

Pada Rab, 4 Des 2024 13.38, edoaurahman ***@***.***> menulis:
